services:
  - type: web
    name: cicd-pipeline-demo
    runtime: docker-image
    image: ghcr.io/klu2300032775/cicd-pipeline-demo:latest
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: APP_VERSION
        value: 1.0.0
